// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_from_airtable_index from "./routes/api/from/airtable/index.tsx";
import * as $api_from_airtable_to_googleCal_id_ from "./routes/api/from/airtable/to/googleCal/[id].ts";
import * as $api_from_airtable_to_ics_id_ from "./routes/api/from/airtable/to/ics/[id].ts";
import * as $api_from_airtable_to_office365_id_ from "./routes/api/from/airtable/to/office365/[id].ts";
import * as $api_from_airtable_to_outlook_id_ from "./routes/api/from/airtable/to/outlook/[id].ts";
import * as $api_from_airtable_to_preview from "./routes/api/from/airtable/to/preview.tsx";
import * as $api_from_airtable_to_yahoo_id_ from "./routes/api/from/airtable/to/yahoo/[id].ts";
import * as $api_from_notion_index from "./routes/api/from/notion/index.tsx";
import * as $api_from_notion_to_googleCal_url_ from "./routes/api/from/notion/to/googleCal/[...url].ts";
import * as $api_from_notion_to_ics_url_ from "./routes/api/from/notion/to/ics/[...url].ts";
import * as $api_from_notion_to_ics_index from "./routes/api/from/notion/to/ics/index.tsx";
import * as $api_from_notion_to_office365_url_ from "./routes/api/from/notion/to/office365/[...url].ts";
import * as $api_from_notion_to_outlook_url_ from "./routes/api/from/notion/to/outlook/[...url].ts";
import * as $api_from_notion_to_preview from "./routes/api/from/notion/to/preview.tsx";
import * as $api_from_notion_to_yahoo_url_ from "./routes/api/from/notion/to/yahoo/[...url].ts";
import * as $api_from_url_index from "./routes/api/from/url/index.tsx";
import * as $api_from_url_to_googleCal_url_ from "./routes/api/from/url/to/googleCal/[...url].ts";
import * as $api_from_url_to_ics_url_ from "./routes/api/from/url/to/ics/[...url].ts";
import * as $api_from_url_to_office365_url_ from "./routes/api/from/url/to/office365/[...url].ts";
import * as $api_from_url_to_outlook_url_ from "./routes/api/from/url/to/outlook/[...url].ts";
import * as $api_from_url_to_preview from "./routes/api/from/url/to/preview.tsx";
import * as $api_from_url_to_yahoo_url_ from "./routes/api/from/url/to/yahoo/[...url].ts";
import * as $api_toCalFormat_googleCal_url_ from "./routes/api/toCalFormat/googleCal/[...url].ts";
import * as $api_toCalFormat_googleCal_from_notion_url_ from "./routes/api/toCalFormat/googleCal/from/notion/[...url].ts";
import * as $api_toCalFormat_ics_from_index from "./routes/api/toCalFormat/ics/from/index.ts";
import * as $api_toCalFormat_ics_from_notion_url_ from "./routes/api/toCalFormat/ics/from/notion/[...url].ts";
import * as $api_toCalFormat_ics_from_notion_index from "./routes/api/toCalFormat/ics/from/notion/index.ts";
import * as $api_toCalFormat_ics_index from "./routes/api/toCalFormat/ics/index.ts";
import * as $api_toCalFormat_office365_url_ from "./routes/api/toCalFormat/office365/[...url].ts";
import * as $api_toCalFormat_outlook_url_ from "./routes/api/toCalFormat/outlook/[...url].ts";
import * as $api_toCalFormat_yahoo_url_ from "./routes/api/toCalFormat/yahoo/[...url].ts";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $RRule from "./islands/RRule.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/from/airtable/index.tsx": $api_from_airtable_index,
    "./routes/api/from/airtable/to/googleCal/[id].ts":
      $api_from_airtable_to_googleCal_id_,
    "./routes/api/from/airtable/to/ics/[id].ts": $api_from_airtable_to_ics_id_,
    "./routes/api/from/airtable/to/office365/[id].ts":
      $api_from_airtable_to_office365_id_,
    "./routes/api/from/airtable/to/outlook/[id].ts":
      $api_from_airtable_to_outlook_id_,
    "./routes/api/from/airtable/to/preview.tsx": $api_from_airtable_to_preview,
    "./routes/api/from/airtable/to/yahoo/[id].ts":
      $api_from_airtable_to_yahoo_id_,
    "./routes/api/from/notion/index.tsx": $api_from_notion_index,
    "./routes/api/from/notion/to/googleCal/[...url].ts":
      $api_from_notion_to_googleCal_url_,
    "./routes/api/from/notion/to/ics/[...url].ts": $api_from_notion_to_ics_url_,
    "./routes/api/from/notion/to/ics/index.tsx": $api_from_notion_to_ics_index,
    "./routes/api/from/notion/to/office365/[...url].ts":
      $api_from_notion_to_office365_url_,
    "./routes/api/from/notion/to/outlook/[...url].ts":
      $api_from_notion_to_outlook_url_,
    "./routes/api/from/notion/to/preview.tsx": $api_from_notion_to_preview,
    "./routes/api/from/notion/to/yahoo/[...url].ts":
      $api_from_notion_to_yahoo_url_,
    "./routes/api/from/url/index.tsx": $api_from_url_index,
    "./routes/api/from/url/to/googleCal/[...url].ts":
      $api_from_url_to_googleCal_url_,
    "./routes/api/from/url/to/ics/[...url].ts": $api_from_url_to_ics_url_,
    "./routes/api/from/url/to/office365/[...url].ts":
      $api_from_url_to_office365_url_,
    "./routes/api/from/url/to/outlook/[...url].ts":
      $api_from_url_to_outlook_url_,
    "./routes/api/from/url/to/preview.tsx": $api_from_url_to_preview,
    "./routes/api/from/url/to/yahoo/[...url].ts": $api_from_url_to_yahoo_url_,
    "./routes/api/toCalFormat/googleCal/[...url].ts":
      $api_toCalFormat_googleCal_url_,
    "./routes/api/toCalFormat/googleCal/from/notion/[...url].ts":
      $api_toCalFormat_googleCal_from_notion_url_,
    "./routes/api/toCalFormat/ics/from/index.ts":
      $api_toCalFormat_ics_from_index,
    "./routes/api/toCalFormat/ics/from/notion/[...url].ts":
      $api_toCalFormat_ics_from_notion_url_,
    "./routes/api/toCalFormat/ics/from/notion/index.ts":
      $api_toCalFormat_ics_from_notion_index,
    "./routes/api/toCalFormat/ics/index.ts": $api_toCalFormat_ics_index,
    "./routes/api/toCalFormat/office365/[...url].ts":
      $api_toCalFormat_office365_url_,
    "./routes/api/toCalFormat/outlook/[...url].ts":
      $api_toCalFormat_outlook_url_,
    "./routes/api/toCalFormat/yahoo/[...url].ts": $api_toCalFormat_yahoo_url_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/RRule.tsx": $RRule,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
